init:
- ps: cinst jdk8
- ps: >-
    $base = "https://raw.githubusercontent.com/technomancy/leiningen/"

    $lein = $base + "stable/bin/lein.bat"

    (new-object net.webclient).DownloadFile($lein, 'lein.bat')
- lein self-install

install:
- lein deps

test_script:
- "lein do clean, test, jar"

build: off

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 'c5c15b507e38d0fb09cbaab6ec6ad1e63ffcc437'
  artifact: /target/.*\.jar/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
